/* eslint-disable no-unused-vars */
import { savingNewGroup, addNewGroup, setActiveGroup, updateGroup, setGroups } from "./teachersSlice";
import { api } from "../../api";
import { getCurrentUserToken } from "../../firebase/providers";
import { loadGroups } from "../../helpers/loadGroups";

export const startCreatingGroup = (groupName, key) => {

    return async (dispatch, getState) => {

        dispatch(savingNewGroup());

        const newGroup = {
            groupName,
            groupCode: key,
            accessToken: '', // This will be generated by the backend
        }

        try {

            // Retrieves the current user's token to send it to the Flask backend and verify the user's identity
            const token = await getCurrentUserToken();

            // Calls the Flask-Axios backend to create the group using the token
            const resp = await api.post('/teachers/creategroup', {
                groupName,
                key,
            }, {
                headers: {
                    'Authorization': `Bearer ${token.token}`,
                    'Content-Type': 'application/json',
                }
            })

            // Spread the original group object and add the accessToken from the response
            const newGroupCopy = { ...newGroup };
            newGroupCopy.accessToken = resp.data.group.accessToken;

            dispatch(addNewGroup(newGroupCopy));
            dispatch(setActiveGroup(newGroupCopy));

        } catch (error) {
            return null;
        }

    }
}

export const startLoadingGroups = () => {

    return async (dispatch) => {

        const groups = await loadGroups();
        dispatch(setGroups(groups));
    }

}
